### ISSUE TITLE
is it available to predict segmental duplications

### ISSUE THREAD

**Issue by AlisaGU** [sfu-compbio/mrsfast#15]
Hi, 
A paper said mrsfast can predict segmental duplications based on read depth. However, I didn't find this function. Did I miss anything?

![image](https://user-images.githubusercontent.com/38097726/148357038-6befab66-519e-42b2-aa7c-4b57356d9c66.png)
from the Supplementary Material of Great ape genetic diversity and population history

**Comment by fhach** [comment]
mrsFAST is an aligner, its output may be used to detect segmental duplication. I think they have analyzed read-depths from mapping files generated by mrsFAST.

If you are interested in segmental duplications, please check out our other tools for segmental duplications:
https://github.com/vpc-ccg/sedef
https://github.com/0xTCG/biser
