### ISSUE TITLE
-e invalid

### ISSUE THREAD

**Issue by SZ-qing** [sfu-compbio/mrsfast#17]
Dear developer, 
I have been using version 3.4.2 of mrsfast for alignment, 
and I've found that the **-e parameter** is ineffective. It always retains its default value. Here are the results:
For -e 4:
![image](https://github.com/sfu-compbio/mrsfast/assets/85827219/b46c0759-feac-4dba-a6f5-582189c15301)
For -e 9: 
![image](https://github.com/sfu-compbio/mrsfast/assets/85827219/eeca73ba-1742-4672-b137-e2cbda938f3e)

**Comment by fhach** [comment]
Hi,

selection of parameter `e` relies on your read length and the windows size used to index the genome. For example if you are using `ws` 12 and your read length is 24, the maximum number of errors allowed is 1. This will ensure that it will remain fully sensitive and will not lose any mapping location. In general the cap can be calculated by `(read_length/window_size)-1`.

Also remember lower `ws` values may result in higher computation time.
