### ISSUE TITLE
Errors: 8

### ISSUE THREAD

**Issue by SayakaKayumi** [sfu-compbio/mrsfast#2]
Hi, 
I encountered a problem. I ran the command and mrsfast-ultra. (Version: 3.4.0 Build Date: Tue Dec 27 19:23:16 ACDT 2016)
The command line I was using `mrsfast --search ref.fasta --pe --discordant-vh --threads 24 --seqcomp --seq1 ${}.R1.fastq.gz --seq2 ${}.R2.fastq.gz --crop ${readlength} 
--min ${minimum} --max ${maximum} --disable-nohits` 
Input files are paired-end and consistent length. 

It gave me Errors:8.
##### # Errors: 8
How can I fix this?
Thank you.

**Comment by fhach** [comment]
I am not sure I am following you on this. Since you have not specified number of mismatches (-e option), mrsfast is automatically setting it up to 8 (#Errors: 8).  To double check, you can set -e 6 and see the output.

**Comment by SayakaKayumi** [comment]
Thank you for your reply. I tried with -e option, and I didn't receive any error messages.  
The command line I was using is
`mrsfast --search ref.fa --pe --discordant-vh --threads 24 -e 6 --seqcomp --seq1 ${}.R1.fastq.gz --seq2 ${}.R2.fastq.gz --crop ${readlength} --min ${minimum} --max ${maximum} --disable-nohits`
### # Threads: 24
I also tried `-e 8` option, and It didn't give me any error.
Thank you.

**Comment by fhach** [comment]
# Errors: 8
is not error number but rather showing what program defaults its -e option. 

You may also want to reduce number of the threads you are using to 8 or 4 for optimal speed up.

**Comment by SayakaKayumi** [comment]
Okay.
Thank you so much.

**Comment by archiandrews** [comment]
Hello

I am trying to map paired-end samples using mrsFAST and I am encountering the below error (ERR: Inconsistent read length). Any idea on how to resolve this? 

[@fn-0001 mrsfast-3.4.0]$ ./mrsfast --search /gpfs/data/lab/raa04/conifer/hg19.fa --seq1 /gpfs/data/shuktilab/veeraa04/conifer/AMV1_R1.fastq --seq2 /gpfs/data/lab/raa04/conifer/AMV1_R2.fastq --pe -o output.sam -e 2 --crop 36
==> This version is compiled without any SSE4 optimization <==
# Threads: 1
-----------------------------------------------------------------------------------------------------------
|     Genome Name |    Loading Time |    Mapping Time | Memory Usage(M) |  Total Mappings    Mapped reads |
-----------------------------------------------------------------------------------------------------------
ERR: Inconsistent read length for @NB501457:38:HWNTKBGXY:1:11101:16080:1853
