### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by niina05** [sfu-compbio/mrsfast#3]
I received segmentation fault
`14285 Segmentation fault      (core dumped)$path/mrsfast --search GRCh38_full_analysis_set.fa --pe --discordant-vh --seq1 R1.group_1.fastq --seq2 R2.group_1.fastq --crop 148 --min 297 --max 848 > mrsfast.seq1.log 2>&1`

The result of make command gave me the following,
`cc -fno-pic -DMRSFAST_VERSION=\""3.4.0"\" -DBUILD_DATE=\""Thu May 18 21:00:15 ACST 2017"\" -DSSE4=0 -O2   -c -o baseFAST.o baseFAST.c
cc -fno-pic -DMRSFAST_VERSION=\""3.4.0"\" -DBUILD_DATE=\""Thu May 18 21:00:15 ACST 2017"\" -DSSE4=0 -O2   -c -o Sort.o Sort.c
cc -fno-pic -DMRSFAST_VERSION=\""3.4.0"\" -DBUILD_DATE=\""Thu May 18 21:00:15 ACST 2017"\" -DSSE4=0 -O2   -c -o MrsFAST.o MrsFAST.c
cc -fno-pic -DMRSFAST_VERSION=\""3.4.0"\" -DBUILD_DATE=\""Thu May 18 21:00:15 ACST 2017"\" -DSSE4=0 -O2   -c -o Common.o Common.c
cc -fno-pic -DMRSFAST_VERSION=\""3.4.0"\" -DBUILD_DATE=\""Thu May 18 21:00:15 ACST 2017"\" -DSSE4=0 -O2   -c -o CommandLineParser.o CommandLineParser.c
cc -fno-pic -DMRSFAST_VERSION=\""3.4.0"\" -DBUILD_DATE=\""Thu May 18 21:00:15 ACST 2017"\" -DSSE4=0 -O2   -c -o RefGenome.o RefGenome.c
cc -fno-pic -DMRSFAST_VERSION=\""3.4.0"\" -DBUILD_DATE=\""Thu May 18 21:00:15 ACST 2017"\" -DSSE4=0 -O2   -c -o HashTable.o HashTable.c
cc -fno-pic -DMRSFAST_VERSION=\""3.4.0"\" -DBUILD_DATE=\""Thu May 18 21:00:15 ACST 2017"\" -DSSE4=0 -O2   -c -o Reads.o Reads.c
cc -fno-pic -DMRSFAST_VERSION=\""3.4.0"\" -DBUILD_DATE=\""Thu May 18 21:00:15 ACST 2017"\" -DSSE4=0 -O2   -c -o Output.o Output.c
cc -fno-pic -DMRSFAST_VERSION=\""3.4.0"\" -DBUILD_DATE=\""Thu May 18 21:00:15 ACST 2017"\" -DSSE4=0 -O2   -c -o SNPReader.o SNPReader.c
gcc -w baseFAST.o Sort.o MrsFAST.o Common.o CommandLineParser.o RefGenome.o HashTable.o Reads.o Output.o SNPReader.o  HELP.o -o mrsfast  -lz -lm -pthread -lpthread
cc -fno-pic -DMRSFAST_VERSION=\""3.4.0"\" -DBUILD_DATE=\""Thu May 18 21:00:15 ACST 2017"\" -DSSE4=0 -O2   -c -o SNPIndexer.o SNPIndexer.c
gcc SNPIndexer.o -o snp_indexer  -lz -lm -pthread -lpthread`

But the log file contains `==> This version is compiled without any SSE4 optimization <==`
I tried multiple times, but it worked until first chr3 and it stopped.

I hope you gives me any advice on this issue.

**Comment by fhach** [comment]
How many reads are you trying to map? Can you try mapping 1M reads first and see if you get the seg fault?

SSE4 optimization is for higher speed but if Makefile decided to compile it without, it means your machine did not support the instruction set. You may ignore that message.

**Comment by niina05** [comment]
Thank you for your reply. I tried with 1M reads, but the result is still the same.
`3206 Segmentation fault      (core dumped) mrsfast --search GRCh38_full_analysis_set.fa --pe --discordant-vh --seq1 mrsfast.test.R1.fastq --seq2 mrsfast.test.R2.fastq --crop 148 --min 297 --max 848 `

**Comment by fhach** [comment]
Can you please repeat it with 50K and 500K reads. If 50K crashes, can you send me the 50K plus link to the exact reference you are using so I can test it and debug it?

**Comment by niina05** [comment]
Thank you for your reply.
I just tried with different reference file and it didn't give me segmentation fault.
So problem was probably in my reference file and I could fix it.

Thank you for your time.
Please close this issue.

**Comment by dopameinfy** [comment]
I have the same issue when I am indexing my reference genome.
`"/var/spool/torque/mom_priv/jobs/4094396.m2.SC: line 3:  6876 Segmentation fault"`
I am not using a human genome and this genome has ~30000 contigs, could this be a problem?
