### ISSUE TITLE
ERR: Inconsistent read length while mapping

### ISSUE THREAD

**Issue by archiandrews** [sfu-compbio/mrsfast#5]
Hello

I am trying to map paired-end samples using mrsFAST and I am encountering the below error (ERR: Inconsistent read length). Any idea on how to resolve this?

[@fn-0001 mrsfast-3.4.0]$ ./mrsfast --search /gpfs/data/lab/raa04/conifer/hg19.fa --seq1 /gpfs/data/lab/raa04/conifer/AMV1_R1.fastq --seq2 /gpfs/data/lab/raa04/conifer/AMV1_R2.fastq --pe -o output.sam -e 2 --crop 36
==> This version is compiled without any SSE4 optimization <==
Threads: 1
| Genome Name | Loading Time | Mapping Time | Memory Usage(M) | Total Mappings Mapped reads |

ERR: Inconsistent read length for @NB501457:38:HWNTKBGXY:1:11101:16080:1853

**Comment by fhach** [comment]
Hi,

I believe you still have reads that are shorter than 36bp. Most likely that is the reason you are getting incosistent read length error. 

You can use this command to look at the distrubution of your read length:

```
cat /gpfs/data/lab/raa04/conifer/AMV1_R1.fastq | awk '{getline; print length($0); getline;getline}' | sort -u 
cat /gpfs/data/lab/raa04/conifer/AMV1_R2.fastq | awk '{getline; print length($0); getline;getline}' | sort -u 
```

**Comment by eleniadam** [comment]
Hello @fhach ,

I am currently running mrsfast (3.4.2) with : 
mrsfast --search ref.fasta --seq inputfile.fastq -e 10

and I get this error (and then the program terminates) :
ERR: Inconsistent read length for @readID

where there is a read (readID) with a length different from the length of the first read in the file. 

After some testing, it seems that the software will only run if all the reads have the same length. I tried the suggestion you had made in this issue and I used reads of length greater than 36bp (and with lengths that differ) but that did not seem to affect the issue. 

Could you please let me know if this is the case, i.e. that all reads must be of the same length?

Thank you,
Eleni
