### ISSUE TITLE
option -e not working

### ISSUE THREAD

**Issue by Arthurhe** [sfu-compbio/mrsfast#6]
Hi,

I'm trying to map some 14bp sequences to the human genome with max 2 mismatches allowed. However, no matter how I adjust the -e option, the program only checks for the perfect match.

for example:
mrsfast --search hg19.fasta --seq mrsfast_test.fq  -e 2 --threads 4 -o mrsfast_out.sam
\# Threads: 4
\# Error: 0 (full sensitivity)
..

Is there a way to fix this?

I'm using mrsFAST-Ultra Version: 3.4.0.

Thank you!

**Comment by fhach** [comment]
Hi,

It is not a bug. Your sequences are just too short. The window size that is used to build the index is 12bp.  

max error = \ceil( l / ws) - 1  = (14/12) - 1 = 0

**Comment by Arthurhe** [comment]
> Hi,
> 
> It is not a bug. Your sequences are just too short. The window size that is used to build the index is 12bp.
> 
> max error = \ceil( l / ws) - 1 = (14/12) - 1 = 0

Hi,

Could I get what I want by re-indexing using 6bp as window size?

Thanks!
